display task comments
NUS-ISS-SE-Group06/task-tracker pull request #53
Opened 2024-04-13 16:04 UTC by oWahyudi

2024-04-14 16:15 UTC, sivabalaji1986 requested changes

2024-04-14 16:15 UTC, sivabalaji1986 commented on src/services/commentService.js
> + const fetchCommentList = async (accessToken,taskId) => {
Can you please get this token from Cookie instead of getting this from parameter

2024-04-14 16:15 UTC, sivabalaji1986 commented on src/services/commentService.js
> +        const response = await fetch(BASE_URL + "/comment-info/comment-list/"+taskId, {
Can you please keep the path also in Constant?
You can add the taskId in the commentService but the comment path should come from constant

2024-04-16 08:57 UTC, oWahyudi commented
code review fixes

2024-04-17 13:25 UTC, William-Dou reviewed
reviewed for the comment part integration

2024-04-17 13:25 UTC, merged